tasks:
  - name: Setup environment and PHP/Composer dependencies
    openMode: split-left
    init: |
      cp .env.example .env &&
      sed -i "s#APP_URL=http://localhost#APP_URL=$(gp url 8000)#g" .env
      sed -i "s#GITPOD_VITE_URL=#GITPOD_VITE_URL=$(gp url 5173)#g" .env
      touch database/database.sqlite
      composer install
      php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="chris@crose.co.uk" --admin-password="123456"

ports:
  - port: 5173
    onOpen: ignore
    visibility: public
    name: Node Server for Vite
